### ISSUE TITLE
能研究一下如何分页吗？

### ISSUE THREAD

**Issue by luckypoem** [sadhen/sadhen.com#1]
我也搭建了一个hakyll博客：http://hk.smt.biz.st/ ,不过不知道如何分页。

**Comment by sadhen** [comment]
我对前端一窍不通，这个blog是fork自xinitrc.de，你可以去看看它现在的样子

**Comment by luckypoem** [comment]
hi.

root@22500:~/sadhen.com-site# ghc --make site.hs
[5 of 5] Compiling Main             ( site.hs, site.o )

site.hs:15:64:
    Module `Data.Time.Format' does not export `defaultTimeLocale'
root@22500:~/sadhen.com-site#

怎么解决？搜了一下，没找到解决办法

**Comment by sadhen** [comment]
可能你没有用最新的ghc和相关的依赖，我在这个commit：https://github.com/sadhen/sadhen.com/commit/92d365a2f37c16a3e3f0e11557ca1e807d2d1a94 做了一些改动，你可以试试这个commit之前的

**Comment by luckypoem** [comment]
hi.

这次运行ghc --make site.hs ,成功生成了可执行文件site.(上次失败是因为你用的是hakyll 3?.现在改为hakyll4了？）

root@AR:/usr/local/sadhen.com-site# ls
about.html    css	  Plugins    site     site.o
archive.html  index.html  README.md  _site    springer-lncs.csl
blog	      LICENSE	  ref.bib    site.hi  static
_cache	      partials	  scripts    site.hs  templates
root@AR:/usr/local/sadhen.com-site#

不过运行./site build,运行到最后还是出错：
...
updated blog/2015-11-27-packaging-libmdcpp.md
  updated blog/2016-01-01-book-list-2015.md
  updated blog/2016-02-26-confessions-of-love.md
  updated blog/2016-05-21-cytoscape-intro.md
  updated blog/2016-06-05-scala-tools-intro.md
  updated blog/2016-07-31-scala-graph-dot.md
  updated templates/month-item.html
  updated templates/month.html
  updated archive.html
  updated atom.xml
  [ERROR] Hakyll.Core.UnixFilter.unixFilterWith: sass -s --no-cache -I. --compass --scss --style compressed gave exit code 1
root@AR:/usr/local/sadhen.com-site#

如何解决？

**Comment by luckypoem** [comment]
哦。运行apt-get install ruby-sass ruby-compass yui-compressor之后，就正常了
